[package]
name = "sql_server_detector"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.49", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
futures-util = "0.3"